apiVersion: v1
kind: Service
metadata:
  name: {{ nginx_ingress_nodeport['name'] }}
  namespace: {{ nginx_ingress_ctl_kube_namespace }}
spec:
  type: NodePort
  ports:
{% for item in nginx_ingress_nodeport['ports'] %}
  - name: {{ item['name'] }}
    port: {{ item['port'] }}
    targetPort: {{ item['target_port'] }}
    protocol: {{ item['protocol'] }}
{% endfor %}
  selector:
{% for item in nginx_ingress_nodeport['selectors'] %}
    {{ item['name'] }}: {{ item['value'] }}
{% endfor %}