apiVersion: v1
data:
  auth: {{ htpasswd_content_encoded }}
kind: Secret
type: Opaque
metadata:
  name: {{ nginx_ingress_ctl_basic_auth_secret_name }}
  namespace: {{ nginx_ingress_ctl_kube_namespace }}
