---

- name: KUBE NGINX INGRESS CONTROLLER HPA TASK | Apply HPA Config
  k8s:
    api_key: "{{ kube_auth_api_key }}"
    ca_cert: "{{ kube_ca_path }}"
    validate_certs: false
    host: "{{ kube_api_url }}"
    state: present
    definition: "{{ lookup('template', '{{ nginx_ingress_ctl_hpa }}') }}"
    validate:
      fail_on_error: yes
  when: nginx_ingress_ctl_hpa is defined and nginx_ingress_ctl_hpa != ""

- name: KUBE NGINX INGRESS CONTROLLER HPA TASK | Get a List of All HPAs
  k8s_info:
    api_key: "{{ kube_auth_api_key }}"
    ca_cert: "{{ kube_ca_path }}"
    validate_certs: false
    host: "{{ kube_api_url }}"
    kind: HorizontalPodAutoscaler
    namespace: "{{ nginx_ingress_ctl_kube_namespace }}"
  register: hpa_list_after
  when: nginx_ingress_ctl_hpa is defined and nginx_ingress_ctl_hpa != ""

- debug:
    var: hpa_list_after.resources
  when: hpa_list_after is defined

