---

- name: KUBE NGINX INGRESS CONTROLLER PRE TASKS | Import Kube CA
  copy:
    content: "{{ kube_ca_base | b64decode }}"
    dest: "{{ kube_ca_path }}"
  when: kube_ca_path is defined and kube_ca_path != ""
  tags: ["always"]

- name: KUBE NGINX INGRESS CONTROLLER PRE TASKS | Ensure That the Namespace Exists 
  community.kubernetes.k8s:
    api_key: "{{ kube_auth_api_key }}"
    ca_cert: "{{ kube_ca_path | default(omit) }}"
    validate_certs: "{{ kube_validate_certs }}"
    host: "{{ kube_api_url }}"
    kind: Namespace
    api_version: v1
    name: "{{ nginx_ingress_ctl_kube_namespace }}"
    state: present
  tags: ["always"]
