apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-{{ nginx_ingress_ctl_name }}
  namespace: {{ nginx_ingress_ctl_kube_namespace }}
spec:
  maxReplicas: {{ nginx_ingress_ctl_hpa_config['max_replicas'] }}
  minReplicas: {{ nginx_ingress_ctl_hpa_config['min_replicas'] }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ nginx_ingress_ctl_name }}
  metrics:
  - type: Resource
    resource:
      ### https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ nginx_ingress_ctl_hpa_config['target_cpu_utilization_percentage'] }}