kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ nginx_ingress_ctl_configmap_name | default('nginx-config') }}
  namespace: {{ nginx_ingress_ctl_kube_namespace }}
data:
{% if nginx_ingress_ctl_global_log_format is defined and nginx_ingress_ctl_global_log_format != "" %}
  log-format: "{{ nginx_ingress_ctl_global_log_format }}"
{% endif %}
{% if nginx_ingress_ctl_global_real_ip_header is defined and nginx_ingress_ctl_global_real_ip_header != "" %}
  real-ip-header: "{{ nginx_ingress_ctl_global_real_ip_header }}"
{% endif %}
{% if nginx_ingress_ctl_global_real_ip_recursive is defined and nginx_ingress_ctl_global_real_ip_recursive != "" %}
  real-ip-recursive: "{{ nginx_ingress_ctl_global_real_ip_recursive }}"
{% endif %}
{% if nginx_ingress_ctl_global_set_real_ip_from is defined and nginx_ingress_ctl_global_set_real_ip_from != "" %}
  set-real-ip-from: "{{ nginx_ingress_ctl_global_set_real_ip_from }}"
{% endif %}
{% if nginx_ingress_ctl_global_extra_conf is defined and nginx_ingress_ctl_global_extra_conf != "" %}
{{ nginx_ingress_ctl_global_extra_conf | to_nice_yaml(width=800) | indent(width=2, indentfirst=False) }}
{% endif %}